KOCHKA: remove tests
The CI is again failing on the following error:

```
TypeError: /home/runner/work/universe/universe/src/kochka.com.mx/.babelrc.js: Error while loading config - /home/runner/work/universe/universe/src/kochka.com.mx/.babelrc.js: Error while loading config - (0 , _helperCompilationTargets(...).isBrowsersQueryValid) is not a function
```

I do not understand what's going on but I am starting to think it's some bug in Jest/Babel because it always affects only this project. Maybe the dots in the directory name are an issue?

See: https://pipelines.actions.githubusercontent.com/6LWmR8MQe2JtpFMQf5GbBmVmIFmVK0LpsGoz1zB2djLBvvW1i4/_apis/pipelines/1/runs/20731/signedlogcontent/3?urlExpires=2021-04-20T14%3A51%3A01.4978004Z&urlSigningMethod=HMACV1&urlSignature=WgI01lOmVmZ6kbfK%2BL86v9IE3H6Vi6Whye6dpZshG%2Bg%3D

I will keep investigating.