Downgrade '@babel/core' dependency
Some tests started failing with the following error:

```
Error while loading config - (0 , _helperCompilationTargets(...).isBrowsersQueryValid) is not a function
```

The failing seem to be quite stable on CI but locally the errors seem to be fairly random.

I found this issue which looks similar: https://github.com/babel/babel/issues/12732

So I tried to enforce only one `@babel/core` dependency (instead of having several conflicting versions) and all seem to be good now (at least locally).